name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build the Docker image
        run: docker build Docker -t bkram/docker-ansible-lint:latest

      - name: Tag image destination
        run: docker tag bkram/docker-ansible-lint:latest ${{ secrets.REGISTRY }}/bkram/docker-ansible-lint:latest

      - name: Push to registry
        run: docker push ${{ secrets.REGISTRY }}/bkram/docker-ansible-lint:latest
